# Generated by Django 6.0 on 2026-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="blog/"),
        ),
    ]
